server:
  context-path: /seller
  port: 8083
#debug: true
spring:
  datasource:
    #    url: jdbc:h2:mem:manager;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://127.0.0.1:3306/seller?user=root&password=123456&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true # 开启jpaSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # org.hibernate.dialect.MySQL5Dialect：新版本的mysql配置
        # org.hibernate.dialect.MySQLDialect ：老版本的mysql 配置
        dialect: org.hibernate.dialect.MySQLDialect
  jackson: # json转换时格式化日期
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 # 格林威治标准时间+8个时区
logging:
  level:
    com.googlecode.jsonrpc4j: debug # jsonrpc4j日志级别
rpc:
  client:
    url: http://localhost:8081/manager # rpc调用的地址
    basePackage: com.lvmen.api # 扫描的包，rpc调用的接口