spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?user=root&password=123456&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
server:
  port: 8081
  context-path: /manager # 应用上下文路径
logging:
  level:
    com.googlecode.jsonrpc4j: debug
