spring:
  datasource:
#    url: jdbc:h2:mem:manager;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://127.0.0.1:3306/manager?user=root&password=123456&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
  jackson: # json转换时格式化日期
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 # 格林威治标准时间+8个时区

server:
  port: 8081
  context-path: /manager # 应用上下文路径
logging:
  level: debug
swagger:
  groupName: manger
  basePackage: com.lvmen.manager.controller
